package me.gibson.captchanotifier.client;

import java.util.Arrays;

public enum ScrambleAnswers {
    ADMIN("admin"),
    AFTERNOON("afternoon"),
    ALLAY("allay"),
    AMETHYST("amethyst"),
    ANIMATIONS("animations"),
    ANVIL("anvil"),
    APPLE("apple"),
    AQUA("aqua"),
    ARMOR("armor"),
    ARROW("arrow"),
    AXE("axe"),
    AZURE("azure"),
    BACKPACK("backpack"),
    BADLANDS("badlands"),
    BAMBOO("bamboo"),
    BANEOFARTHROPODS("baneofarthropods"),
    BARREL("barrel"),
    BEACON("beacon"),
    BEDROCK("bedrock"),
    BLACKDYE("blackdye"),
    BLACKSTONE("blackstone"),
    BLASTFURNACE("blastfurnace"),
    BLASTPROTECTION("blastprotection"),
    BLAZEROD("blazerod"),
    BLUEDYE("bluedye"),
    BOAT("boat"),
    BONE("bone"),
    BOOK("book"),
    BOOKSHELF("bookshelf"),
    BOTTLE("bottle"),
    BREWING("brewing"),
    BRICK("brick"),
    BROWN("brown"),
    BUCKET("bucket"),
    BUILDER("builder"),
    CACTUS("cactus"),
    CAKE("cake"),
    CARPET("carpet"),
    CAULDRON("cauldron"),
    CHARCOAL("charcoal"),
    CHICKEN("chicken"),
    CHESTPLATE("chestplate"),
    CHORUS("chorus"),
    COAL("coal"),
    COBBLESTONE("cobblestone"),
    COLOSSAL("colossal"),
    CORAL("coral"),
    CORNFLOWER("cornflower"),
    COW("cow"),
    CRAFTING("crafting"),
    CRYSTAL("crystal"),
    DARKBLUE("darkblue"),
    DARKGREEN("darkgreen"),
    DARKRED("darkred"),
    DECORATION("decoration"),
    DEPTHSTRIDER("depthstrider"),
    DIAMOND("diamond"),
    DIRT("dirt"),
    DISCORD("discord"),
    DONATOR("donator"),
    DOOR("door"),
    DRAGONHEAD("dragonhead"),
    DRIPSTONE("dripstone"),
    DROPPER("dropper"),
    DUST("dust"),
    EFFICIENCY("efficiency"),
    ELDERGUARDIAN("elderguardian"),
    ELF("elf"),
    ELYTRA("elytra"),
    EMERALD("emerald"),
    END("end"),
    ENDERDRAGON("enderdragon"),
    ENDSTONE("endstone"),
    ENVOY("envoy"),
    FACTORY("factory"),
    FEATHER("feather"),
    FENCE("fence"),
    FIRE("fire"),
    FIREWORK("firework"),
    FISHING("fishing"),
    FISHINGROD("fishingrod"),
    FLOWER("flower"),
    FORTUNE("fortune"),
    FOX("fox"),
    FROG("frog"),
    FROSTWALKER("frostwalker"),
    GATE("gate"),
    GLOWLICHEN("glowlichen"),
    GOAT("goat"),
    GOLDENCARROT("goldencarrot"),
    GRAYDYE("graydye"),
    GRAY("gray"),
    GREENDYE("greendye"),
    GRINDER("grinder"),
    GUNPOWDER("gunpowder"),
    HAYBALE("haybale"),
    HEALING("healing"),
    HELMET("helmet"),
    HELPER("helper"),
    HERO("hero"),
    HILLS("hills"),
    HIPPO("hippo"),
    HOE("hoe"),
    HONEY("honey"),
    HUSK("husk"),
    ICE("ice"),
    IMPALING("impaling"),
    IRONDOOR("irondoor"),
    IRONGOLEM("irongolem"),
    JOCKEY("jockey"),
    JUNGLE("jungle"),
    KOTH("koth"),
    LAMP("lamp"),
    LAPISLAZULI("lapislazuli"),
    LEAPING("leaping"),
    LECTERN("lectern"),
    LEVER("lever"),
    LIGHT("light"),
    LIGHTNINGROD("lightningrod"),
    LIMEDYE("limedye"),
    LIME("lime"),
    LOYALTY("loyalty"),
    LUCKOFTHESEA("luckofthesea"),
    LYANNE("lyanne"),
    MAGMACUBE("magmacube"),
    MAGMA("magma"),
    MASTERY("mastery"),
    MATERIALS("materials"),
    MENORAH("menorah"),
    MESA("mesa"),
    METEOR("meteor"),
    MILK("milk"),
    MILKYWAY("milkyway"),
    MINECART("minecart"),
    MODERATOR("moderator"),
    MONSTER("monster"),
    MOON("moon"),
    MOOSHROOM("mooshroom"),
    MORNING("morning"),
    MOUNTAINS("mountains"),
    MULTIPLIER("multiplier"),
    MULTISHOT("multishot"),
    MUSHROOM("mushroom"),
    MYCELIUM("mycelium"),
    NETHER("nether"),
    NETHERBRICK("netherbrick"),
    NETHERRACK("netherrack"),
    NOOT("noot"),
    NOTEBLOCK("noteblock"),
    OBSERVER("observer"),
    OBSIDIAN("obsidian"),
    OGPLAYER("ogplayer"),
    ORANGEDYE("orangedye"),
    ORNAMENT("ornament"),
    OWNER("owner"),
    OXEYE("oxeye"),
    PANTS("pants"),
    PARTNER("partner"),
    PENGUIN("penguin"),
    PEONY("peony"),
    PHANTOM("phantom"),
    PICKAXE("pickaxe"),
    PIERCING("piercing"),
    PLAIN("plain"),
    PLANK("plank"),
    PLOTS("plots"),
    POGGERS("poggers"),
    POISON("poison"),
    POPROCKS("poprocks"),
    POT("pot"),
    POTATO("potato"),
    PRESSURE("pressure"),
    PROJECTILEPROTECTION("projectileprotection"),
    PROTECTION("protection"),
    PUNCH("punch"),
    QUARTZ("quartz"),
    RABBIT("rabbit"),
    RAIL("rail"),
    RAVAGER("ravager"),
    REDDYE("reddye"),
    REDSAND("redsand"),
    REPEATER("repeater"),
    RESPIRATION("respiration"),
    RIPTIDE("riptide"),
    ROTTENFLESH("rottenflesh"),
    RUBY("ruby"),
    SAITO16("saito16"),
    SAITO("saito"),
    SAND("sand"),
    SAPLING("sapling"),
    SAVANNA("savanna"),
    SCUTE("scute"),
    SHARD("shard"),
    SHARPNESS("sharpness"),
    SHIELD("shield"),
    SILVERFISH("silverfish"),
    SLAB("slab"),
    SLEEP("sleep"),
    SLIME("slime"),
    SMITE("smite"),
    SNOW("snow"),
    SNOWBALL("snowball"),
    SOULSPEED("soulspeed"),
    SPAWN("spawn"),
    SPECTRAL("spectral"),
    SPIKE("spike"),
    SPLASH("splash"),
    SPONGE("sponge"),
    SQUID("squid"),
    STAINED("stained"),
    STARBURST("starburst"),
    STICKYPISTON("stickypiston"),
    STRAY("stray"),
    STRIDER("strider"),
    STRENGTH("strength"),
    STRING("string"),
    SUGAR("sugar"),
    SUMMONER("summoner"),
    SUNFLOWER("sunflower"),
    SWEEPINGEDGE("sweepingedge"),
    THORNS("thorns"),
    TOTEM("totem"),
    TOTEMOFUNDYING("totemofundying"),
    TREE("tree"),
    TUNDRA("tundra"),
    TULIP("tulip"),
    TWIZZLER("twizzler"),
    UNBREAKING("unbreaking"),
    VISION("vision"),
    WARZONE("warzone"),
    WATCH("watch"),
    WHEAT("wheat"),
    WITCH("witch"),
    WORKBENCH("workbench"),
    YELLOW("yellow"),
    YOUTUBE("youtube"),
    ZOGLIN("zoglin"),
    ZOMBIEVILLAGER("zombievillager");

    private final String answer;
    private final String sortedChars;

    ScrambleAnswers(String answer) {
        this.answer = answer;
        this.sortedChars = sortString(answer);
    }

    public String getAnswer() {
        return answer;
    }

    private static String sortString(String input) {
        char[] chars = input.toLowerCase().toCharArray();
        Arrays.sort(chars);
        return new String(chars);
    }

    public static String solve(String scrambled) {
        if (scrambled == null || scrambled.isEmpty()) {
            return null;
        }

        String scrambledSorted = sortString(scrambled);

        for (ScrambleAnswers answer : values()) {
            if (answer.sortedChars.equals(scrambledSorted)) {
                return answer.answer;
            }
        }

        return null;
    }

    public static boolean hasAnswer(String scrambled) {
        return solve(scrambled) != null;
    }
}
